
package vistas;


import controlador.conexion;
import modelo.producto;
import controlador.productosql;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class editarproducto extends javax.swing.JInternalFrame {

    producto producto = new producto();
    conexion conexion = new conexion();
    productosql productosql = new productosql();
    DefaultTableModel tabla = new DefaultTableModel();


    public editarproducto() {
        initComponents();
        conexion = new conexion();
           limpiarcampos();
       deshabilitar();
    }
    
 


public void habilitar() {
    
  
        this.TXTCODIGO_PRODUCTO.setEnabled(true);
        this.TXTNOMBRE_PRODUCTO.setEnabled(true);
        this.TXTCOSTO_PRODUCTO.setEnabled(true);
        this.TXTPRECIO_PRODUCTO.setEnabled(true);
        this.TXTMATERIAL_PRODUCTO.setEnabled(true);
        this.TXTPRESENTACION_PRODUCTO.setEnabled(true);
        
        this.TXTPESO_PRODUCTO.setEnabled(true);
        this.TXTCAPACIDAD_PRODUCTO.setEnabled(true);
        this.TXTDESCRIPCION_PRODUCTO.setEnabled(true);
        
        this.btactualizar.setEnabled(true);
        this.bteliminar.setEnabled(true);
    
        
    }
    
public void deshabilitar() {
    
  
     this.TXTCODIGO_PRODUCTO.setEnabled(false);
        this.TXTNOMBRE_PRODUCTO.setEnabled(false);
        this.TXTCOSTO_PRODUCTO.setEnabled(false);
        this.TXTPRECIO_PRODUCTO.setEnabled(false);
        this.TXTCODIGO_PRODUCTO.setEnabled(false);
        this.TXTMATERIAL_PRODUCTO.setEnabled(false);
        this.TXTPRESENTACION_PRODUCTO.setEnabled(false);
        this.TXTPESO_PRODUCTO.setEnabled(false);
        this.TXTCAPACIDAD_PRODUCTO.setEnabled(false);
        this.TXTDESCRIPCION_PRODUCTO.setEnabled(false);
        
        this.btactualizar.setEnabled(false);
  this.bteliminar.setEnabled(false);
    
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btactualizar = new javax.swing.JButton();
        btcerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bteliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TXTCODIGO_PRODUCTO = new javax.swing.JTextField();
        TXTNOMBRE_PRODUCTO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTCOSTO_PRODUCTO = new javax.swing.JTextField();
        TXTPRECIO_PRODUCTO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTMATERIAL_PRODUCTO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTPRESENTACION_PRODUCTO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTPESO_PRODUCTO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TXTCAPACIDAD_PRODUCTO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXTDESCRIPCION_PRODUCTO = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproducto = new javax.swing.JTable();
        btmostrar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(0, 153, 153));
        setClosable(true);
        setTitle("CONTROL DE PRODUCTO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/page-refresh-icon.png"))); // NOI18N
        btactualizar.setText("actualizar");
        btactualizar.setEnabled(false);
        btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 40));

        btcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-project-development-close-icon.png"))); // NOI18N
        btcerrar.setText("cerrar");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 90, 40));

        jPanel2.setBackground(java.awt.Color.blue);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTROL DE PRODUCTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 22, 370, -1));

        bteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/File-Delete-icon.png"))); // NOI18N
        bteliminar.setText("eliminar");
        bteliminar.setEnabled(false);
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bteliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 110, 40));

        jLabel2.setText("CODIGO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 94, 174, -1));

        TXTCODIGO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCODIGO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTCODIGO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCODIGO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTCODIGO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 91, 153, -1));

        TXTNOMBRE_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBRE_PRODUCTOActionPerformed(evt);
            }
        });
        TXTNOMBRE_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBRE_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTNOMBRE_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 122, 153, -1));

        jLabel3.setText("NOMBRE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 126, 137, -1));

        jLabel4.setText("COSTO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 151, 116, 24));

        TXTCOSTO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCOSTO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTCOSTO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCOSTO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTCOSTO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 150, 153, -1));

        TXTPRECIO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRECIO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTPRECIO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPRECIO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTPRECIO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 181, 153, -1));

        jLabel6.setText("PRECIO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 178, 116, 24));

        TXTMATERIAL_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTMATERIAL_PRODUCTOActionPerformed(evt);
            }
        });
        TXTMATERIAL_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTMATERIAL_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTMATERIAL_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 208, 153, -1));

        jLabel5.setText("MATERIAL:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 208, -1, 20));

        jLabel7.setText("PRESENTACION:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 239, 142, 20));

        TXTPRESENTACION_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRESENTACION_PRODUCTOActionPerformed(evt);
            }
        });
        TXTPRESENTACION_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPRESENTACION_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTPRESENTACION_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 239, 153, -1));

        jLabel9.setText("PESO (KG):");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 142, 20));

        TXTPESO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPESO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTPESO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPESO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTPESO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 153, -1));

        jLabel10.setText("CAPACIDAD (L):");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 142, 20));

        TXTCAPACIDAD_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCAPACIDAD_PRODUCTOActionPerformed(evt);
            }
        });
        TXTCAPACIDAD_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCAPACIDAD_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTCAPACIDAD_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 153, -1));

        jLabel11.setText("DESCRIPCION:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 142, 20));

        TXTDESCRIPCION_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDESCRIPCION_PRODUCTOActionPerformed(evt);
            }
        });
        TXTDESCRIPCION_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTDESCRIPCION_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTDESCRIPCION_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 153, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 380, 400));

        tablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaproducto);

        btmostrar.setText("Mostrar o actualizar tabla");
        btmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btmostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btmostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarcampos() {
    
  
        this.TXTCODIGO_PRODUCTO.setText("");
        this.TXTNOMBRE_PRODUCTO.setText("");
        this.TXTCOSTO_PRODUCTO.setText("");
        this.TXTPRECIO_PRODUCTO.setText("");
        this.TXTMATERIAL_PRODUCTO.setText("");
        this.TXTPRESENTACION_PRODUCTO.setText("");
        
        this.TXTPESO_PRODUCTO.setText("");
        this.TXTCAPACIDAD_PRODUCTO.setText("");
        this.TXTDESCRIPCION_PRODUCTO.setText("");
        
    }
    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed

      ////////////////////////77  
        try {
            if (conexion.getConexion() != null) {
                if ((this.TXTCODIGO_PRODUCTO.getText().isEmpty())
                        || (this.TXTNOMBRE_PRODUCTO.getText().isEmpty())
                        || (this.TXTCOSTO_PRODUCTO.getText().isEmpty())
                        || (this.TXTPRECIO_PRODUCTO.getText().isEmpty())
                        || (this.TXTMATERIAL_PRODUCTO.getText().isEmpty())
                        || (this.TXTPRESENTACION_PRODUCTO.getText().isEmpty())
                        || (this.TXTPESO_PRODUCTO.getText().isEmpty())
                        || (this.TXTCAPACIDAD_PRODUCTO.getText().isEmpty())
                        || (this.TXTDESCRIPCION_PRODUCTO.getText().isEmpty())) {
                    //incorrecto
                    JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos o llene los campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    
                    //producto.setPRECIO_PRODUCTO(Double.parseDouble(TXTNOMBRE_PRODUCTO.getText()));
                     
                    producto.setCODIGO_PRODUCTO(TXTCODIGO_PRODUCTO.getText());
                    producto.setNOMBRE_PRODUCTO(TXTNOMBRE_PRODUCTO.getText());
                    producto.setCOSTO_PRODUCTO(TXTCOSTO_PRODUCTO.getText());
                    producto.setPRECIO_PRODUCTO(TXTPRECIO_PRODUCTO.getText());
                    producto.setMATERIAL_PRODUCTO(TXTMATERIAL_PRODUCTO.getText());
                    producto.setPRESENTACION_PRODUCTO(TXTPRESENTACION_PRODUCTO.getText());
                    producto.setPESO_PRODUCTO(TXTPESO_PRODUCTO.getText());
                    producto.setCAPACIDAD_PRODUCTO(TXTCAPACIDAD_PRODUCTO.getText());
                    producto.setDESCRIPCION_PRODUCTO(TXTDESCRIPCION_PRODUCTO.getText());
                    
                    productosql.actualizarproducto(producto);
                    deshabilitar();
                    limpiarcampos();
                     mostrartabla();
                    
                }
            } else {
              JOptionPane.showMessageDialog(null, "Error en Conexión PostgreSQL 9.0 ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Error en los datos", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());

    }                                        


        
    
        
    }//GEN-LAST:event_btactualizarActionPerformed

    private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarActionPerformed

        try {
            if (conexion.getConexion() != null) {
                dispose();
                conexion.CloseConexion();
            } else {
                JOptionPane.showMessageDialog(null, "Error en Conexión. Revisa tu conexion", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
 System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btcerrarActionPerformed

      public void mostrartabla() {

          try {
            if (conexion.getConexion() != null) {
                tabla.setColumnCount(0);
                tabla.setRowCount(0);
                this.tablaproducto.setModel(tabla);
 
                tabla.addColumn("ID_PRODUCTO");
                tabla.addColumn("CODIGO_PRODUCTO");
                tabla.addColumn("NOMBRE_PRODUCTO");
                tabla.addColumn("COSTO_PRODUCTO");
                tabla.addColumn("PRECIO_PRODUCTO");
                tabla.addColumn("MATERIAL_PRODUCTO");
                tabla.addColumn("PRESENTACION_PRODUCTO");
                tabla.addColumn("PESO_PRODUCTO");
                tabla.addColumn("CAPACIDAD_PRODUCTO");
                tabla.addColumn("DESCRIPCION_PRODUCTO");
                
                Object[] datos = new Object[10];
                List<producto > lis = productosql.MostrarTodos();
                        
                for (producto  li : lis) {
                    datos[0] = li.getID_PRODUCTO();
                    datos[1] = li.getCODIGO_PRODUCTO();
                    datos[2] = li.getNOMBRE_PRODUCTO();
                    datos[3] = li.getCOSTO_PRODUCTO();
                    datos[4] = li.getPRECIO_PRODUCTO();
                    datos[5] = li.getMATERIAL_PRODUCTO();
                    datos[6] = li.getPRESENTACION_PRODUCTO();
                    datos[7] = li.getPESO_PRODUCTO();
                    datos[8] = li.getCAPACIDAD_PRODUCTO();
                    datos[9] = li.getDESCRIPCION_PRODUCTO();
               
                    tabla.addRow(datos);
                }
                
            } else {
 JOptionPane.showMessageDialog(null, "Error en Conexión. Revisa tu conexion", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
 System.out.println(e.getMessage());
        }    
        
          
    }
    
    private void btmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmostrarActionPerformed
       
        mostrartabla();
    
    }                                          

    private void jTableEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {                                              

        
    }//GEN-LAST:event_btmostrarActionPerformed

 
    
    
    private void tablaproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproductoMouseClicked
      
           
        int fila = this.tablaproducto.getSelectedRow();
   
        
        
        int idobjtabla = (int) this.tablaproducto.getValueAt(fila, 0);
        
        
         
        try {
            if (conexion.getConexion() != null) {
              habilitar();
              
                producto = productosql.obtenerproductoid(idobjtabla);
                
                
//this.TXTNOMBRE_PRODUCTO.setText(String.valueOf(producto.getPRECIO_PRODUCTO()));             
                
                this.TXTCODIGO_PRODUCTO.setText(producto.getCODIGO_PRODUCTO());
                this.TXTNOMBRE_PRODUCTO.setText(producto.getNOMBRE_PRODUCTO());            
                this.TXTCOSTO_PRODUCTO.setText(String.valueOf(producto.getCOSTO_PRODUCTO()));
                this.TXTPRECIO_PRODUCTO.setText(String.valueOf(producto.getPRECIO_PRODUCTO()));
                this.TXTMATERIAL_PRODUCTO.setText(producto.getMATERIAL_PRODUCTO());
                this.TXTPRESENTACION_PRODUCTO.setText(producto.getPRESENTACION_PRODUCTO());
                this.TXTPESO_PRODUCTO.setText(String.valueOf(producto.getPESO_PRODUCTO()));
                this.TXTCAPACIDAD_PRODUCTO.setText(producto.getCAPACIDAD_PRODUCTO());
                this.TXTDESCRIPCION_PRODUCTO.setText(producto.getDESCRIPCION_PRODUCTO());
                
   
                
            } else {
 JOptionPane.showMessageDialog(null, "Error en Conexión. Revisa tu conexion", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
 System.out.println(ex.getMessage());
        }
    
        
        
        
        
    }//GEN-LAST:event_tablaproductoMouseClicked

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
       
         try {
            int op = JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar", "Pregunta", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                productosql.eliminarproducto(producto.getID_PRODUCTO());
                    deshabilitar();
                    limpiarcampos();
                     mostrartabla();
            } else {
                 JOptionPane.showMessageDialog(null, "Seleccione un campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(null, "Datos no encontrados", "Error", JOptionPane.ERROR_MESSAGE);
        }
         
        
        
        
    }//GEN-LAST:event_bteliminarActionPerformed

    private void TXTCODIGO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCODIGO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCODIGO_PRODUCTOActionPerformed

    private void TXTCODIGO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCODIGO_PRODUCTOKeyTyped
           if (this.TXTCODIGO_PRODUCTO.getText().length() >= 6) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_TXTCODIGO_PRODUCTOKeyTyped

    private void TXTNOMBRE_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBRE_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBRE_PRODUCTOActionPerformed

    private void TXTNOMBRE_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBRE_PRODUCTOKeyTyped

              
       char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }   if (this.TXTNOMBRE_PRODUCTO.getText().length() >= 20) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

        
    }//GEN-LAST:event_TXTNOMBRE_PRODUCTOKeyTyped

    private void TXTCOSTO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCOSTO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCOSTO_PRODUCTOActionPerformed

    private void TXTCOSTO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCOSTO_PRODUCTOKeyTyped
          if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTCOSTO_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTCOSTO_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTCOSTO_PRODUCTOKeyTyped

    private void TXTPRECIO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRECIO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRECIO_PRODUCTOActionPerformed

    private void TXTPRECIO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPRECIO_PRODUCTOKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTPRECIO_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTPRECIO_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTPRECIO_PRODUCTOKeyTyped

    private void TXTMATERIAL_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTMATERIAL_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTMATERIAL_PRODUCTOActionPerformed

    private void TXTMATERIAL_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTMATERIAL_PRODUCTOKeyTyped
        // TODO add your handling code here:
           char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
           
        }   if (this.TXTMATERIAL_PRODUCTO.getText().length() >= 20) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTMATERIAL_PRODUCTOKeyTyped

    private void TXTPRESENTACION_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRESENTACION_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRESENTACION_PRODUCTOActionPerformed

    private void TXTPRESENTACION_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPRESENTACION_PRODUCTOKeyTyped
    char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }       if (this.TXTPRESENTACION_PRODUCTO.getText().length() >= 20) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTPRESENTACION_PRODUCTOKeyTyped

    private void TXTPESO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPESO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPESO_PRODUCTOActionPerformed

    private void TXTPESO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPESO_PRODUCTOKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTPESO_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTPESO_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TXTPESO_PRODUCTOKeyTyped

    private void TXTCAPACIDAD_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCAPACIDAD_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCAPACIDAD_PRODUCTOActionPerformed

    private void TXTCAPACIDAD_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCAPACIDAD_PRODUCTOKeyTyped
     if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTCAPACIDAD_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTCAPACIDAD_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_TXTCAPACIDAD_PRODUCTOKeyTyped

    private void TXTDESCRIPCION_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDESCRIPCION_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDESCRIPCION_PRODUCTOActionPerformed

    private void TXTDESCRIPCION_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDESCRIPCION_PRODUCTOKeyTyped
if (this.TXTDESCRIPCION_PRODUCTO.getText().length() >= 30) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 30 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }          
                                                   

    }//GEN-LAST:event_TXTDESCRIPCION_PRODUCTOKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTCAPACIDAD_PRODUCTO;
    private javax.swing.JTextField TXTCODIGO_PRODUCTO;
    private javax.swing.JTextField TXTCOSTO_PRODUCTO;
    private javax.swing.JTextField TXTDESCRIPCION_PRODUCTO;
    private javax.swing.JTextField TXTMATERIAL_PRODUCTO;
    private javax.swing.JTextField TXTNOMBRE_PRODUCTO;
    private javax.swing.JTextField TXTPESO_PRODUCTO;
    private javax.swing.JTextField TXTPRECIO_PRODUCTO;
    private javax.swing.JTextField TXTPRESENTACION_PRODUCTO;
    private javax.swing.JButton btactualizar;
    private javax.swing.JButton btcerrar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btmostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproducto;
    // End of variables declaration//GEN-END:variables
}
