
package vistas;


import modelo.maquina;
import controlador.conexion;

import controlador.maquinasql;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;

public class nuevamaquina extends javax.swing.JInternalFrame {

  //CREAMOS UNA CONEXION
    conexion conexion = new conexion();
 
//CREAMOS LOS OBJECTOS 
    maquinasql maquinasql = new maquinasql();
    maquina maquina = new maquina();


    public nuevamaquina() {
        initComponents();
        conexion = new conexion();
        limpiarcampos(); //LLAMAMOS AL METODO LIMPIAR CAMPOS
       
    }
    
//LIMPIAR LOS TEXT BOX DEL FORMULARIO
public void limpiarcampos() {
    
  
        this.TXTCODIGO_MAQUINARIA.setText("");
        this.TXTNOMBRE_MAQUINARIA.setText("");
        this.TXTCAPACIDAD_MAQUINARIA.setText("");
        this.TXTPESO_MAQUINARIA.setText("");
        this.TXTENERGIA_MAQUINARIA.setText("");
        this.TXTDESCRIPCION_MAQUINARIA.setText("");

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTCODIGO_MAQUINARIA = new javax.swing.JTextField();
        TXTCAPACIDAD_MAQUINARIA = new javax.swing.JTextField();
        TXTENERGIA_MAQUINARIA = new javax.swing.JTextField();
        TXTPESO_MAQUINARIA = new javax.swing.JTextField();
        TXTDESCRIPCION_MAQUINARIA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTNOMBRE_MAQUINARIA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btguardar = new javax.swing.JButton();
        btcerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnuevo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 153, 153));
        setClosable(true);
        setTitle("INGRESO DE NUEVA MAQUINARIA");

        jLabel2.setText("CODIGO:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("CAPACIDAD (HPB):");

        TXTCODIGO_MAQUINARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCODIGO_MAQUINARIAActionPerformed(evt);
            }
        });
        TXTCODIGO_MAQUINARIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCODIGO_MAQUINARIAKeyTyped(evt);
            }
        });

        TXTCAPACIDAD_MAQUINARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCAPACIDAD_MAQUINARIAActionPerformed(evt);
            }
        });
        TXTCAPACIDAD_MAQUINARIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCAPACIDAD_MAQUINARIAKeyTyped(evt);
            }
        });

        TXTENERGIA_MAQUINARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTENERGIA_MAQUINARIAActionPerformed(evt);
            }
        });
        TXTENERGIA_MAQUINARIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTENERGIA_MAQUINARIAKeyTyped(evt);
            }
        });

        TXTPESO_MAQUINARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPESO_MAQUINARIAActionPerformed(evt);
            }
        });
        TXTPESO_MAQUINARIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPESO_MAQUINARIAKeyTyped(evt);
            }
        });

        TXTDESCRIPCION_MAQUINARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDESCRIPCION_MAQUINARIAActionPerformed(evt);
            }
        });
        TXTDESCRIPCION_MAQUINARIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTDESCRIPCION_MAQUINARIAKeyTyped(evt);
            }
        });

        jLabel5.setText("CONSUMO DE ENERGIA (KW):");

        jLabel6.setText("PESO (KG):");

        TXTNOMBRE_MAQUINARIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBRE_MAQUINARIAActionPerformed(evt);
            }
        });
        TXTNOMBRE_MAQUINARIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBRE_MAQUINARIAKeyTyped(evt);
            }
        });

        jLabel7.setText("DESCRIPCION:");

        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-document-save-icon.png"))); // NOI18N
        btguardar.setText("guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });

        btcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-project-development-close-icon.png"))); // NOI18N
        btcerrar.setText("cerrar");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.blue);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NUEVA MAQUINA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/File-New-icon.png"))); // NOI18N
        btnuevo.setText("nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TXTCODIGO_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(TXTNOMBRE_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(TXTCAPACIDAD_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(TXTPESO_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(TXTDESCRIPCION_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTENERGIA_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(TXTCODIGO_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(TXTNOMBRE_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXTCAPACIDAD_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(TXTPESO_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTENERGIA_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTDESCRIPCION_MAQUINARIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTCODIGO_MAQUINARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCODIGO_MAQUINARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCODIGO_MAQUINARIAActionPerformed

    private void TXTCAPACIDAD_MAQUINARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCAPACIDAD_MAQUINARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCAPACIDAD_MAQUINARIAActionPerformed

    private void TXTENERGIA_MAQUINARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTENERGIA_MAQUINARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTENERGIA_MAQUINARIAActionPerformed

    private void TXTPESO_MAQUINARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPESO_MAQUINARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPESO_MAQUINARIAActionPerformed

    private void TXTDESCRIPCION_MAQUINARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDESCRIPCION_MAQUINARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDESCRIPCION_MAQUINARIAActionPerformed

    private void TXTNOMBRE_MAQUINARIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBRE_MAQUINARIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBRE_MAQUINARIAActionPerformed

  
    //GUARDA EL REGUISTRO EN LA BASE DE DATOS
    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed

        try {
            if (conexion.getConexion() != null) {

                //declaramos a las variables los valores de los textbox
                String VTXTCODIGO_MAQUINARIA = this.TXTCODIGO_MAQUINARIA.getText();
                String VTXTNOMBRE_MAQUINARIA = this.TXTNOMBRE_MAQUINARIA.getText();
                
             
                 DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
                 separadoresPersonalizados.setDecimalSeparator('.');
                 DecimalFormat df = new DecimalFormat("#.##",separadoresPersonalizados);
                 
                 
                 
                 String VTXTCAPACIDAD_MAQUINARIA = df.format(Double.parseDouble(TXTCAPACIDAD_MAQUINARIA.getText()));
               
                        
                 String VTXTPESO_MAQUINARIA = df.format(Double.parseDouble(TXTPESO_MAQUINARIA.getText()));
                 String VTXTENERGIA_MAQUINARIA = df.format(Double.parseDouble(TXTENERGIA_MAQUINARIA.getText()));
                      
        
                String VTXTDESCRIPCION_MAQUINARIA = this.TXTDESCRIPCION_MAQUINARIA.getText();


                
                //finalizamo la declaracion a las variables los valores de los textbox

                if ((this.TXTCODIGO_MAQUINARIA.getText().isEmpty())
                        || (this.TXTNOMBRE_MAQUINARIA.getText().isEmpty())
                        || (this.TXTCAPACIDAD_MAQUINARIA.getText().isEmpty())
                        || (this.TXTPESO_MAQUINARIA.getText().isEmpty())
                        || (this.TXTENERGIA_MAQUINARIA.getText().isEmpty())
                        || (this.TXTDESCRIPCION_MAQUINARIA.getText().isEmpty())

                ) {
                    //incorrecto
                    JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos o llene los campos vacios", "Error", JOptionPane.ERROR_MESSAGE);

                } else {

                    //conexion cn = new conexion();


                    //asiganmos la variables a los set del objeto
                    maquina.setCODIGO_MAQUINARIA(VTXTCODIGO_MAQUINARIA);
                    maquina.setNOMBRE_MAQUINARIA(VTXTNOMBRE_MAQUINARIA);
                    maquina.setCAPACIDAD_MAQUINARIA(VTXTCAPACIDAD_MAQUINARIA);
                    maquina.setPESO_MAQUINARIA(VTXTPESO_MAQUINARIA);
                    maquina.setENERGIA_MAQUINARIA(VTXTENERGIA_MAQUINARIA);
                    maquina.setDESCRIPCION_MAQUINARIA(VTXTDESCRIPCION_MAQUINARIA);


                    //insertamos el objeto en la base de datos llamando al metodo 
               
                    maquinasql.insertarmaquina(maquina);
                    //llamamos al metodo limpiar campo
                    limpiarcampos();

                }

            } else {
                //no conexion
                JOptionPane.showMessageDialog(null, "Error en Conexión PostgreSQL 9.0 ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //vacio
            JOptionPane.showMessageDialog(null, "No existen datos veriifique la informacion ingresada que se correcta", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btguardarActionPerformed

    private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarActionPerformed

        try {
            if (conexion.getConexion() != null) {
                dispose();
                conexion.CloseConexion();
            } else {
                JOptionPane.showMessageDialog(null, "Error en Conexión. Revisa tu conexion", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btcerrarActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        limpiarcampos();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void TXTNOMBRE_MAQUINARIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBRE_MAQUINARIAKeyTyped
      
               char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        if (this.TXTNOMBRE_MAQUINARIA.getText().length() >= 20) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
 
    }//GEN-LAST:event_TXTNOMBRE_MAQUINARIAKeyTyped

    private void TXTCODIGO_MAQUINARIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCODIGO_MAQUINARIAKeyTyped

        if (this.TXTCODIGO_MAQUINARIA.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_TXTCODIGO_MAQUINARIAKeyTyped

    private void TXTCAPACIDAD_MAQUINARIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCAPACIDAD_MAQUINARIAKeyTyped
           
              
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTCAPACIDAD_MAQUINARIA.getText().contains(".")){
          evt.consume();
 }if (this.TXTCAPACIDAD_MAQUINARIA.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_TXTCAPACIDAD_MAQUINARIAKeyTyped

    private void TXTPESO_MAQUINARIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPESO_MAQUINARIAKeyTyped
    
        
         if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTPESO_MAQUINARIA.getText().contains(".")){
          evt.consume();
 }if (this.TXTPESO_MAQUINARIA.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_TXTPESO_MAQUINARIAKeyTyped

    private void TXTENERGIA_MAQUINARIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTENERGIA_MAQUINARIAKeyTyped
           
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTENERGIA_MAQUINARIA.getText().contains(".")){
          evt.consume();
 }if (this.TXTENERGIA_MAQUINARIA.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_TXTENERGIA_MAQUINARIAKeyTyped

    private void TXTDESCRIPCION_MAQUINARIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDESCRIPCION_MAQUINARIAKeyTyped

        if (this.TXTDESCRIPCION_MAQUINARIA.getText().length() >= 25) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 25 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_TXTDESCRIPCION_MAQUINARIAKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTCAPACIDAD_MAQUINARIA;
    private javax.swing.JTextField TXTCODIGO_MAQUINARIA;
    private javax.swing.JTextField TXTDESCRIPCION_MAQUINARIA;
    private javax.swing.JTextField TXTENERGIA_MAQUINARIA;
    private javax.swing.JTextField TXTNOMBRE_MAQUINARIA;
    private javax.swing.JTextField TXTPESO_MAQUINARIA;
    private javax.swing.JButton btcerrar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
