
package vistas;

import controlador.conexion;
import modelo.producto;
import controlador.productosql;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;

public class nuevoproducto extends javax.swing.JInternalFrame {

   producto producto = new producto();
    conexion conexion = new conexion();
    productosql productosql = new productosql();


    public nuevoproducto() {
        initComponents();
        conexion = new conexion();
        limpiarcampos();
        

    }
    
 


public void limpiarcampos() {
    
  
        this.TXTCODIGO_PRODUCTO.setText("");
        this.TXTNOMBRE_PRODUCTO.setText("");
        this.TXTCOSTO_PRODUCTO.setText("");
        this.TXTPRECIO_PRODUCTO.setText("");
        this.TXTMATERIAL_PRODUCTO.setText("");
        this.TXTPRESENTACION_PRODUCTO.setText("");
        this.TXTPESO_PRODUCTO.setText("");
        this.TXTCAPACIDAD_PRODUCTO.setText("");
        this.TXTDESCRIPCION_PRODUCTO.setText("");
     

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTCODIGO_PRODUCTO = new javax.swing.JTextField();
        TXTCOSTO_PRODUCTO = new javax.swing.JTextField();
        TXTMATERIAL_PRODUCTO = new javax.swing.JTextField();
        TXTPRECIO_PRODUCTO = new javax.swing.JTextField();
        TXTPRESENTACION_PRODUCTO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTNOMBRE_PRODUCTO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btguardar = new javax.swing.JButton();
        btcerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnuevo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TXTPESO_PRODUCTO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TXTCAPACIDAD_PRODUCTO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXTDESCRIPCION_PRODUCTO = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 153, 153));
        setClosable(true);
        setTitle("INGRESO DE NUEVO PRODUCTO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("CODIGO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 94, 174, -1));

        jLabel3.setText("NOMBRE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 126, 137, -1));

        jLabel4.setText("COSTO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 151, 116, 24));

        TXTCODIGO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCODIGO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTCODIGO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCODIGO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTCODIGO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 91, 153, -1));

        TXTCOSTO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCOSTO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTCOSTO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCOSTO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTCOSTO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 150, 153, -1));

        TXTMATERIAL_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTMATERIAL_PRODUCTOActionPerformed(evt);
            }
        });
        TXTMATERIAL_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTMATERIAL_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTMATERIAL_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 208, 153, -1));

        TXTPRECIO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRECIO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTPRECIO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPRECIO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTPRECIO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 181, 153, -1));

        TXTPRESENTACION_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRESENTACION_PRODUCTOActionPerformed(evt);
            }
        });
        TXTPRESENTACION_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPRESENTACION_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTPRESENTACION_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 239, 153, -1));

        jLabel5.setText("MATERIAL:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 208, -1, 20));

        jLabel6.setText("PRECIO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 178, 116, 24));

        TXTNOMBRE_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBRE_PRODUCTOActionPerformed(evt);
            }
        });
        TXTNOMBRE_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBRE_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTNOMBRE_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 122, 153, -1));

        jLabel7.setText("PRESENTACION:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 239, 142, 20));

        btguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-document-save-icon.png"))); // NOI18N
        btguardar.setText("guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 91, 36));

        btcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-project-development-close-icon.png"))); // NOI18N
        btcerrar.setText("cerrar");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 84, 36));

        jPanel2.setBackground(java.awt.Color.blue);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NUEVO PRODUCTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 22, 300, -1));

        btnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/File-New-icon.png"))); // NOI18N
        btnuevo.setText("nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 84, 36));

        jLabel9.setText("PESO (KG):");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 142, 20));

        TXTPESO_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPESO_PRODUCTOActionPerformed(evt);
            }
        });
        TXTPESO_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTPESO_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTPESO_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 153, -1));

        jLabel10.setText("CAPACIDAD (L):");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 142, 20));

        TXTCAPACIDAD_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCAPACIDAD_PRODUCTOActionPerformed(evt);
            }
        });
        TXTCAPACIDAD_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTCAPACIDAD_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTCAPACIDAD_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 153, -1));

        jLabel11.setText("DESCRIPCION:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 142, 20));

        TXTDESCRIPCION_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDESCRIPCION_PRODUCTOActionPerformed(evt);
            }
        });
        TXTDESCRIPCION_PRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTDESCRIPCION_PRODUCTOKeyTyped(evt);
            }
        });
        jPanel1.add(TXTDESCRIPCION_PRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 153, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTCODIGO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCODIGO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCODIGO_PRODUCTOActionPerformed

    private void TXTCOSTO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCOSTO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCOSTO_PRODUCTOActionPerformed

    private void TXTMATERIAL_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTMATERIAL_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTMATERIAL_PRODUCTOActionPerformed

    private void TXTPRECIO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRECIO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRECIO_PRODUCTOActionPerformed

    private void TXTPRESENTACION_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRESENTACION_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRESENTACION_PRODUCTOActionPerformed

    private void TXTNOMBRE_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBRE_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBRE_PRODUCTOActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed

        try {
            if (conexion.getConexion() != null) {

                //declaramos a las variables los valores de los textbox
                
                String VTXTCODIGO_PRODUCTO = this.TXTCODIGO_PRODUCTO.getText();
                String VTXTNOMBRE_PRODUCTO = this.TXTNOMBRE_PRODUCTO.getText();
                
                
                DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
                 separadoresPersonalizados.setDecimalSeparator('.');
                 DecimalFormat df = new DecimalFormat("#.##",separadoresPersonalizados);
                
                
                String VTXTCOSTO_PRODUCTO = df.format(Double.parseDouble(TXTCOSTO_PRODUCTO.getText()));
             
                 String VTXTPRECIO_PRODUCTO = df.format(Double.parseDouble(TXTPRECIO_PRODUCTO.getText()));
             
                
                String VTXTMATERIAL_PRODUCTO = this.TXTMATERIAL_PRODUCTO.getText();
                String VTXTPRESENTACION_PRODUCTO = this.TXTPRESENTACION_PRODUCTO.getText();
                
                
                String VTXTPESO_PRODUCTO = df.format(Double.parseDouble(TXTPESO_PRODUCTO.getText()));
             
                String VTXTCAPACIDAD_PRODUCTO = df.format(Double.parseDouble(TXTCAPACIDAD_PRODUCTO.getText()));
             
                
                String VTXTDESCRIPCION_PRODUCTO = this.TXTDESCRIPCION_PRODUCTO.getText();

                //finalizamo la declaracion a las variables los valores de los textbox

                if ((this.TXTCODIGO_PRODUCTO.getText().isEmpty())
                    || (this.TXTNOMBRE_PRODUCTO.getText().isEmpty())
                    || (this.TXTCOSTO_PRODUCTO.getText().isEmpty())
                    || (this.TXTPRECIO_PRODUCTO.getText().isEmpty())
                    || (this.TXTMATERIAL_PRODUCTO.getText().isEmpty())
                    || (this.TXTPRESENTACION_PRODUCTO.getText().isEmpty())
                    || (this.TXTPESO_PRODUCTO.getText().isEmpty())
                    || (this.TXTCAPACIDAD_PRODUCTO.getText().isEmpty())
                    || (this.TXTDESCRIPCION_PRODUCTO.getText().isEmpty())
                ) {
                    //incorrecto
                    JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos o llene los campos vacios", "Error", JOptionPane.ERROR_MESSAGE);

                } else {

                    conexion cn = new conexion();

                    //asiganmos la variables a los set del objeto
                    producto.setCODIGO_PRODUCTO(VTXTCODIGO_PRODUCTO);
                    producto.setNOMBRE_PRODUCTO(VTXTNOMBRE_PRODUCTO);
                    producto.setCOSTO_PRODUCTO(VTXTCOSTO_PRODUCTO);
                    producto.setPRECIO_PRODUCTO(VTXTPRECIO_PRODUCTO);
                    producto.setMATERIAL_PRODUCTO(VTXTMATERIAL_PRODUCTO);
                    producto.setPRESENTACION_PRODUCTO(VTXTPRESENTACION_PRODUCTO);
                    
                    producto.setPESO_PRODUCTO(VTXTPESO_PRODUCTO);
                    producto.setCAPACIDAD_PRODUCTO(VTXTCAPACIDAD_PRODUCTO);
                    producto.setDESCRIPCION_PRODUCTO(VTXTDESCRIPCION_PRODUCTO);

                    //insertamos el objeto en la base de datos
                    productosql.insertarproducto(producto);

                    limpiarcampos();

                }

            } else {
                //no conexion
                JOptionPane.showMessageDialog(null, "Error en Conexión PostgreSQL 9.0 ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            //vacio
            JOptionPane.showMessageDialog(null, "No existen datos veriifique la informacion ingresada que se correcta", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btguardarActionPerformed

    private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarActionPerformed

        try {
            if (conexion.getConexion() != null) {
                dispose();
                conexion.CloseConexion();
            } else {
                JOptionPane.showMessageDialog(null, "Error en Conexión. Revisa tu conexion", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
 System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btcerrarActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        limpiarcampos();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void TXTNOMBRE_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBRE_PRODUCTOKeyTyped
      
       char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }   if (this.TXTNOMBRE_PRODUCTO.getText().length() >= 20) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
 
    }//GEN-LAST:event_TXTNOMBRE_PRODUCTOKeyTyped

    private void TXTCODIGO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCODIGO_PRODUCTOKeyTyped
   if (this.TXTCODIGO_PRODUCTO.getText().length() >= 6) {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TXTCODIGO_PRODUCTOKeyTyped

    private void TXTCOSTO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCOSTO_PRODUCTOKeyTyped
          if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTCOSTO_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTCOSTO_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTCOSTO_PRODUCTOKeyTyped

    private void TXTPRECIO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPRECIO_PRODUCTOKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTPRECIO_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTPRECIO_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTPRECIO_PRODUCTOKeyTyped

    private void TXTMATERIAL_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTMATERIAL_PRODUCTOKeyTyped
        // TODO add your handling code here:
           char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
           
        }   if (this.TXTMATERIAL_PRODUCTO.getText().length() >= 20) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTMATERIAL_PRODUCTOKeyTyped

    private void TXTPRESENTACION_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPRESENTACION_PRODUCTOKeyTyped
    char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE) && !(c == KeyEvent.VK_BACK_SPACE)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }       if (this.TXTPRESENTACION_PRODUCTO.getText().length() >= 20) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 20 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_TXTPRESENTACION_PRODUCTOKeyTyped

    private void TXTPESO_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPESO_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPESO_PRODUCTOActionPerformed

    private void TXTPESO_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTPESO_PRODUCTOKeyTyped
       if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTPESO_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTPESO_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TXTPESO_PRODUCTOKeyTyped

    private void TXTCAPACIDAD_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCAPACIDAD_PRODUCTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCAPACIDAD_PRODUCTOActionPerformed

    private void TXTCAPACIDAD_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCAPACIDAD_PRODUCTOKeyTyped
 if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar()!='.' ){
            evt.consume();
  }        if(evt.getKeyChar()=='.'&&TXTCAPACIDAD_PRODUCTO.getText().contains(".")){
          evt.consume();
 }if (this.TXTCAPACIDAD_PRODUCTO.getText().length() >= 6) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 6 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCAPACIDAD_PRODUCTOKeyTyped

    private void TXTDESCRIPCION_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDESCRIPCION_PRODUCTOActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_TXTDESCRIPCION_PRODUCTOActionPerformed

    private void TXTDESCRIPCION_PRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDESCRIPCION_PRODUCTOKeyTyped
if (this.TXTDESCRIPCION_PRODUCTO.getText().length() >= 30) {
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Limite maximo de 30 caracteres", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }          
    }//GEN-LAST:event_TXTDESCRIPCION_PRODUCTOKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTCAPACIDAD_PRODUCTO;
    private javax.swing.JTextField TXTCODIGO_PRODUCTO;
    private javax.swing.JTextField TXTCOSTO_PRODUCTO;
    private javax.swing.JTextField TXTDESCRIPCION_PRODUCTO;
    private javax.swing.JTextField TXTMATERIAL_PRODUCTO;
    private javax.swing.JTextField TXTNOMBRE_PRODUCTO;
    private javax.swing.JTextField TXTPESO_PRODUCTO;
    private javax.swing.JTextField TXTPRECIO_PRODUCTO;
    private javax.swing.JTextField TXTPRESENTACION_PRODUCTO;
    private javax.swing.JButton btcerrar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
